name: Build Kivy App to APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install libtinfo5
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: '3.11'
          buildozer-cmd: 'buildozer android debug'
          work-dir: '.'

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-kivy-apk
          path: bin/*.apk
