name: Build Kivy App to APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: kivy/buildozer-action@v1
        with:
          buildozer-command: 'buildozer android debug'

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-kivy-apk
          path: bin/*.apk
