name: Buildozer Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev clang build-essential

      - name: Install Buildozer and Cython
        run: pip install buildozer cython

      - name: Set up Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;33.0.0" "platforms;android-33"
          export PATH="$PATH:$ANDROID_HOME/build-tools/33.0.0"

      - name: Build and Deploy
        run: buildozer android debug
        env:
          BUILD_USER: ${{ github.actor }}
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/
