name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libmtdev-dev \
            xclip \
            xsel \
            libpng-dev \
            wget

      - name: Instalar Buildozer e Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Instalar SDK e NDK manualmente
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROID_HOME
          
          # Baixa command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm cmdline-tools.zip

          # Adiciona ao PATH
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # Aceita licenças e instala pacotes necessários
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;23.1.7779620"

          # Cria compatibilidade com estrutura antiga que o Buildozer procura
          mkdir -p $ANDROID_HOME/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/* $ANDROID_HOME/tools/bin/ || true

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Upload APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-apk
          path: bin/*.apk
